---
title: "Eine_kleine_Nachtmusik"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Character Diagram


```{r}
library(tidyverse)
library(igraph)
```

## preparation


```{r echo=FALSE}
jinbutsu <- tribble(
     ~Name1, ~Name2,
"佐藤", "藤間",
      "佐藤", "課長",
  "藤間",    "課長",
  "アンケート女性", "佐藤",
  "織田一真", "佐藤",
  "織田一真", "織田(加藤)由美",
  "織田一真", "織田美緒",
  "織田(加藤)由美", "織田美緒",
  "織田一真", "織田一樹",
  "織田(加藤)由美", "織田一樹",
  "織田美緒", "織田一樹",
  "佐藤", "相沢めぐみ",
  "藤間", "藤間妻",
  "藤間", "藤間亜美子",
  "藤間妻", "藤間亜美子",
  "ウィンストン小野学", "板橋(小野)香澄",
  "小野美奈子", "板橋(小野)香澄",
  "ウィンストン小野学", "小野美奈子",
  "小野美奈子", "織田(加藤)由美",
  "山田寛子", "小野美奈子",
  "日高亮一", "小野美奈子",
  "山田寛子", "日高亮一",
  "山田寛子", "斉藤さん",
  "日高亮一", "斉藤さん",
  "小野美奈子", "斉藤さん",
  "ウィンストン小野学", "斉藤さん",
  "藤間", "免許センター女性",
  "免許センター女性", "免許センター女性の子",
  "深堀(笹塚)朱美", "織田美緒",
  "深堀(笹塚)朱美", "久留米(漫才師)和人",
  "織田美緒", "久留米(漫才師)和人",
  "深堀(笹塚)朱美", "久留米邦彦",
  "久留米邦彦", "久留米(漫才師)和人",
  "久留米邦彦", "邦彦の妻(和人の母)",
  "久留米邦彦", "織田美緒",
  "水沼", "織田美緒",
  "水沼", "久留米(漫才師)和人",
  "藤間亜美子", "織田美緒",
  "窪田(高木)結衣", "佳織",
  "窪田(高木)結衣", "山田寛子",
  "照川", "山田寛子",
  "照川", "窪田(高木)結衣",
  "照川", "小久保亜季",
  "窪田(高木)結衣", "小久保亜季",
  "辻井", "小久保亜季",
  "窪田(高木)結衣", "寺内",
  "窪田(高木)結衣", "田中(役員)",
  "田中(役員)", "山田寛子",
  "ウィンストン小野学", "オーエン・スコット",
  "ウィンストン小野学", "松沢ケリー",
  "ウィンストン小野学", "女子高生",
  "ウィンストン小野学", "ラウンドボーイ",
  "女子高生", "ラウンドボーイ"
)
```

```{r}
zzz <- readr::read_csv("tojo_jinbutsu.csv")
```

```{r}
zzz
```

## plot

```{r}
g <- graph.data.frame(zzz, directed = FALSE)
# Remove unnecessary margins
par(mar = c(0, 0, 0, 0))
plot(g, layout = layout.fruchterman.reingold, vertex.size = 8, edge.arrow.size = 0.5)
```

